import { v4 as uuid } from "uuid";

/**
 * Product Database can be added here.
 * You can add products of your wish with different attributes
 * */

export const products = [
  {
    _id: uuid(),
    brand: "Free Authority",
    name: "Dragon Ball Z",
    img: "https://saiyanshop.netlify.app/Assets/img/img13.webp",
    discountedPrice: 499,
    price: 1599,
    discountInPercentage: 50,
    ratings: 1.5,
    peopleLiked: 200,
    categoryName: "non-fiction",
    inWishlist: false,
  },
  {
    _id: uuid(),
    brand: "Free Authority",
    name: "Attack On Titan",
    img: "https://saiyanshop.netlify.app/Assets/img/img7.jpg",
    discountedPrice: 599,
    price: 1599,
    discountInPercentage: 50,
    ratings: 2.5,
    peopleLiked: 200,
    categoryName: "non-fiction",
    inWishlist: false,
  },
  {
    _id: uuid(),
    brand: "Free Authority",
    name: "Dragon Ball Z",
    discountedPrice: 699,
    img: "https://saiyanshop.netlify.app/Assets/img/img8.webp",
    price: 1599,
    discountInPercentage: 50,
    ratings: 3.5,
    peopleLiked: 200,
    categoryName: "non-fiction",
    inWishlist: false,
  },
  {
    _id: uuid(),
    brand: "Free Authority",
    name: "Dragon Ball Z",
    img: "https://saiyanshop.netlify.app/Assets/img/img9.webp",
    discountedPrice: 799,
    price: 1599,
    discountInPercentage: 50,
    ratings: 4.5,
    peopleLiked: 200,
    categoryName: "non-fiction",
    inWishlist: false,
  },
  {
    _id: uuid(),
    brand: "Free Authority",
    name: "Dragon Ball Z",
    img: "https://saiyanshop.netlify.app/Assets/img/img10.webp",
    discountedPrice: 899,
    price: 1599,
    discountInPercentage: 50,
    ratings: 2.5,
    peopleLiked: 200,
    categoryName: "non-fiction",
    inWishlist: false,
  },
  {
    _id: uuid(),
    brand: "Free Authority",
    name: "Dragon Ball Z",
    img: "https://saiyanshop.netlify.app/Assets/img/img11.webp",
    discountedPrice: 599,
    price: 1599,
    discountInPercentage: 50,
    ratings: 3.5,
    peopleLiked: 200,
    categoryName: "non-fiction",
    inWishlist: false,
  },
];
