import { v4 as uuid } from "uuid";

/**
 * Product Database can be added here.
 * You can add products of your wish with different attributes
 * */

export const products = [
  {
    _id: uuid(),
    brand: "Free Authority",
    name: "Dragon Ball Z",
    img: "https://i.ibb.co/r2ZxBCc/APPARELISED-29-1000x.webp",
    discountedPrice: 1299,
    price: 1599,
    discountInPercentage: 20,
    ratings: 4.8,
    peopleLiked: 2.1,
    categoryName: "t-shirts",
    inWishlist: false,
  },
  {
    _id: uuid(),
    brand: "Free Authority",
    name: "Dragon Ball Z",
    img: "https://i.ibb.co/NtddrCX/APPARELISED-32-1000x.webp",
    discountedPrice: 1199,
    price: 1599,
    discountInPercentage: 10,
    ratings: 4.5,
    peopleLiked: 3,
    categoryName: "t-shirts",
    inWishlist: false,
  },
  {
    _id: uuid(),
    brand: "Free Authority",
    name: "Dragon Ball Z",
    discountedPrice: 899,
    img: "https://i.ibb.co/B4Wmmpt/APPARELISED-35-1-1000x.webp",
    price: 1599,
    discountInPercentage: 20,
    ratings: 3.5,
    peopleLiked: 2.3,
    categoryName: "t-shirts",
    inWishlist: false,
  },
  {
    _id: uuid(),
    brand: "Free Authority",
    name: "Dragon Ball Z",
    img: "https://i.ibb.co/pj4cdzC/Untitleddesign-2021-03-31-T190226-184-1000x.webp",
    discountedPrice: 799,
    price: 1599,
    discountInPercentage: 10,
    ratings: 3.5,
    peopleLiked: 3.4,
    categoryName: "t-shirts",
    inWishlist: false,
  },
  {
    _id: uuid(),
    brand: "Free Authority",
    name: "Dragon Ball Z",
    img: "https://i.ibb.co/xgPLv5N/APPARELISED-25-1000x.webp",
    discountedPrice: 999,
    price: 1599,
    discountInPercentage: 40,
    ratings: 3.1,
    peopleLiked: 2.2,
    categoryName: "t-shirts",
    inWishlist: false,
  },
  {
    _id: uuid(),
    brand: "Free Authority",
    name: "Attack On Titan",
    img: "https://i.ibb.co/xDCF64y/ERENJAEGER-2021-05-15-T220643-970-1000x.webp",
    discountedPrice: 799,
    price: 1599,
    discountInPercentage: 40,
    ratings: 3.2,
    peopleLiked: 1.3,
    categoryName: "t-shirts",
    inWishlist: false,
  },
  {
    _id: uuid(),
    brand: "Free Authority",
    name: "Attack On Titan",
    img: "https://i.ibb.co/0tL0YwK/Untitleddesign-2-1000x.webp",
    discountedPrice: 699,
    price: 1599,
    discountInPercentage: 60,
    ratings: 3.3,
    peopleLiked: 1.1,
    categoryName: "t-shirts",
    inWishlist: false,
  },
  {
    _id: uuid(),
    brand: "Free Authority",
    name: "Attack On Titan",
    img: "https://i.ibb.co/n66DmV9/Untitleddesign-2021-04-05-T120913-642-1000x.webp",
    discountedPrice: 899,
    price: 1599,
    discountInPercentage: 50,
    ratings: 3.1,
    peopleLiked: 1.7,
    categoryName: "t-shirts",
    inWishlist: false,
  },
  {
    _id: uuid(),
    brand: "Free Authority",
    name: "Attack On Titan",
    img: "https://i.ibb.co/sVGNLnJ/Untitleddesign-2021-02-17-T104042-044-1000x.webp",
    discountedPrice: 799,
    price: 1599,
    discountInPercentage: 50,
    ratings: 2.2,
    peopleLiked: 2.1,
    categoryName: "t-shirts",
    inWishlist: false,
  },
  {
    _id: uuid(),
    brand: "Free Authority",
    name: "Attack On Titan",
    img: "https://i.ibb.co/MRfw5H6/Untitleddesign-2021-04-04-T223011-161-1000x.webp",
    discountedPrice: 599,
    price: 1599,
    discountInPercentage: 50,
    ratings: 3.8,
    peopleLiked: 2.3,
    categoryName: "t-shirts",
    inWishlist: false,
  },
  {
    _id: uuid(),
    brand: "Free Authority",
    name: "Haikyuu",
    img: "https://i.ibb.co/0yGhVm0/2095197-1.jpg",
    discountedPrice: 599,
    price: 1599,
    discountInPercentage: 50,
    ratings: 3.2,
    peopleLiked: 2.5,
    categoryName: "t-shirts",
    inWishlist: false,
  },
  {
    _id: uuid(),
    brand: "Free Authority",
    name: "Haikyuu",
    img: "https://i.ibb.co/TMx0vhN/16050017-0.jpg",
    discountedPrice: 599,
    price: 1599,
    discountInPercentage: 50,
    ratings: 3.6,
    peopleLiked: 2.7,
    categoryName: "t-shirts",
    inWishlist: false,
  },
  {
    _id: uuid(),
    brand: "Free Authority",
    name: "Haikyuu",
    img: "https://i.ibb.co/rv2Q3GR/16690800-0.jpg",
    discountedPrice: 599,
    price: 1599,
    discountInPercentage: 50,
    ratings: 4.5,
    peopleLiked: 1.7,
    categoryName: "t-shirts",
    inWishlist: false,
  },
  {
    _id: uuid(),
    brand: "Free Authority",
    name: "Haikyuu",
    img: "https://i.ibb.co/0n8y0KW/18260364-0.jpg",
    discountedPrice: 599,
    price: 1599,
    discountInPercentage: 50,
    ratings: 1.5,
    peopleLiked: 3.1,
    categoryName: "t-shirts",
    inWishlist: false,
  },
  {
    _id: uuid(),
    brand: "Free Authority",
    name: "Haikyuu",
    img: "https://i.ibb.co/tKw5X1Y/17967406-1.jpg",
    discountedPrice: 599,
    price: 1599,
    discountInPercentage: 50,
    ratings: 3.2,
    peopleLiked: 2.2,
    categoryName: "t-shirts",
    inWishlist: false,
  },
  {
    _id: uuid(),
    brand: "Free Authority",
    name: "Death Note",
    img: "https://i.ibb.co/g7bJ8cw/567df872df5af244af0389c0aca4a433d3a9688c-original.jpg",
    discountedPrice: 599,
    price: 1599,
    discountInPercentage: 50,
    ratings: 2.5,
    peopleLiked: 2.6,
    categoryName: "t-shirts",
    inWishlist: false,
  },
  {
    _id: uuid(),
    brand: "Free Authority",
    name: "Death Note",
    img: "https://i.ibb.co/T2nmFzm/Death-Note-1500x.webp",
    discountedPrice: 599,
    price: 1599,
    discountInPercentage: 50,
    ratings: 3.6,
    peopleLiked: 1.6,
    categoryName: "t-shirts",
    inWishlist: false,
  },
  {
    _id: uuid(),
    brand: "Free Authority",
    name: "Death Note",
    img: "https://i.ibb.co/ftTKKGH/Death-Note1-1500x.webp",
    discountedPrice: 599,
    price: 1599,
    discountInPercentage: 50,
    ratings: 1.7,
    peopleLiked: 1.9,
    categoryName: "t-shirts",
    inWishlist: false,
  },
  {
    _id: uuid(),
    brand: "Free Authority",
    name: "Death Note",
    img: "https://i.ibb.co/0r0BDNQ/Deathnote-Apple-Face.jpg",
    discountedPrice: 599,
    price: 1599,
    discountInPercentage: 50,
    ratings: 1.8,
    peopleLiked: 1.8,
    categoryName: "t-shirts",
    inWishlist: false,
  },
  {
    _id: uuid(),
    brand: "Free Authority",
    name: "Death Note",
    img: "https://i.ibb.co/G76CBTx/Death-Note-T-Shirt.jpg",
    discountedPrice: 599,
    price: 1599,
    discountInPercentage: 50,
    ratings: 1.6,
    peopleLiked: 1.4,
    categoryName: "t-shirts",
    inWishlist: false,
  },
  {
    _id: uuid(),
    brand: "Free Authority",
    name: "My Hero Academia",
    img: "https://i.ibb.co/Ln6hy9B/blazing-bakugo-t-shirt-219154.jpg",
    discountedPrice: 599,
    price: 1599,
    discountInPercentage: 50,
    ratings: 2.5,
    peopleLiked: 4.1,
    categoryName: "t-shirts",
    inWishlist: false,
  },
  {
    _id: uuid(),
    brand: "Free Authority",
    name: "My Hero Academia",
    img: "https://i.ibb.co/m5CLYHK/My-Hero-Academiaanime-T-Shirt-2.jpg",
    discountedPrice: 599,
    price: 1599,
    discountInPercentage: 50,
    ratings: 3.5,
    peopleLiked: 2.1,
    categoryName: "t-shirts",
    inWishlist: false,
  },
  {
    _id: uuid(),
    brand: "Free Authority",
    name: "My Hero Academia",
    img: "https://i.ibb.co/NSyRQMf/Plus-Ultra-T-Shirt-1.jpg",
    discountedPrice: 599,
    price: 1599,
    discountInPercentage: 50,
    ratings: 2.6,
    peopleLiked: 2.5,
    categoryName: "t-shirts",
    inWishlist: false,
  },
  {
    _id: uuid(),
    brand: "Free Authority",
    name: "My Hero Academia",
    img: "https://i.ibb.co/N9yt6Vz/product-image-1553544628.jpg",
    discountedPrice: 599,
    price: 1599,
    discountInPercentage: 50,
    ratings: 1.5,
    peopleLiked: 2.3,
    categoryName: "t-shirts",
    inWishlist: false,
  },
  {
    _id: uuid(),
    brand: "Free Authority",
    name: "My Hero Academia",
    img: "https://i.ibb.co/hWm5xYN/product-image-1645255741.jpg",
    discountedPrice: 599,
    price: 1599,
    discountInPercentage: 50,
    ratings: 3.1,
    peopleLiked: 1.1,
    categoryName: "t-shirts",
    inWishlist: false,
  },
  {
    _id: uuid(),
    brand: "Free Authority",
    name: "Dr. Stone",
    img: "https://i.ibb.co/XtSJS3W/19-bf0b1967-47b2-454d-9942-95d980e92cc9.jpg",
    discountedPrice: 599,
    price: 1599,
    discountInPercentage: 50,
    ratings: 2.7,
    peopleLiked: 1.3,
    categoryName: "t-shirts",
    inWishlist: false,
  },
  {
    _id: uuid(),
    brand: "Free Authority",
    name: "Dr. Stone",
    img: "https://i.ibb.co/LtTvB4G/Hot-Sale-Anime-Dr-Stone-3d-Printed-T-shirt-Men-women-Fashion-Casual-Harajuku-Short-Sleeve.jpg",
    discountedPrice: 599,
    price: 1599,
    discountInPercentage: 50,
    ratings: 3.7,
    peopleLiked: 3.1,
    categoryName: "t-shirts",
    inWishlist: false,
  },
  {
    _id: uuid(),
    brand: "Free Authority",
    name: "Dr. Stone",
    img: "https://i.ibb.co/P411pYk/Hot-Sale-Anime-Dr-Stone-3d-Printed-T-shirt-Men-women-Fashion-Casual-Harajuku-Short-Sleeve-1.jpg",
    discountedPrice: 599,
    price: 1599,
    discountInPercentage: 50,
    ratings: 2.5,
    peopleLiked: 1.2,
    categoryName: "t-shirts",
    inWishlist: false,
  },
  {
    _id: uuid(),
    brand: "Free Authority",
    name: "Dr. Stone",
    img: "https://i.ibb.co/FnFRLvb/Hot-Sale-Anime-Dr-Stone-3d-Printed-T-shirt-Men-women-Fashion-Casual-Harajuku-Short-Sleeve-4.jpg",
    discountedPrice: 599,
    price: 1599,
    discountInPercentage: 50,
    ratings: 3.2,
    peopleLiked: 1.1,
    categoryName: "t-shirts",
    inWishlist: false,
  },
  {
    _id: uuid(),
    brand: "Free Authority",
    name: "Dr. Stone",
    img: "https://i.ibb.co/vZMyK9t/Hot-Sale-Anime-Dr-Stone-3d-Printed-T-shirt-Men-women-Fashion-Casual-Harajuku-Short-Sleeve-5.jpg",
    discountedPrice: 599,
    price: 1599,
    discountInPercentage: 50,
    ratings: 3.5,
    peopleLiked: 2.1,
    categoryName: "t-shirts",
    inWishlist: false,
  },
];
